name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOCKER_REPO: godatadriven/pyspark

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        DOCKER_TAG: ["3.0.1,3.0,latest", "2.4.5,2.4", "2.3.2,2.3", "2.2.1,2.2", "2.1.2,2.1"]

    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
            DOCKER_TAG="${{ matrix.DOCKER_TAG }}"
            
            SPARK_MAJOR_VERSION=${DOCKER_TAG:0:1}
            if [ ${SPARK_MAJOR_VERSION} = "3" ]; then
                OPENJDK_VERSION=11
            else
                OPENJDK_VERSION=8
            fi
            
            DOCKER_IMAGE_NAME="$DOCKER_REPO:${DOCKER_TAG%%,*}"
            echo ::set-output name=image_name::${DOCKER_IMAGE_NAME}
            
            TAGS="$DOCKER_REPO:${DOCKER_TAG//,/,$DOCKER_REPO:}"
            echo ::set-output name=tags::${TAGS}

            echo ::set-output name=spark_version::${DOCKER_TAG%%,*}
            echo ::set-output name=openjdk_version::${OPENJDK_VERSION}
            
            echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Build image
        uses: docker/build-push-action@v2
        with:
         context: .
         file: ./Dockerfile
         push: false
         tags: ${{ steps.prep.outputs.tags }}
         build-args: |
           OPENJDK_VERSION=${{ steps.prep.outputs.spark_version }}
           SPARK_VERSION=${{ steps.prep.outputs.openjdk_version }}
         labels: |
           org.opencontainers.image.source=${{ github.event.repository.clone_url }}
           org.opencontainers.image.created=${{ steps.prep.outputs.created }}
           org.opencontainers.image.revision=${{ github.sha }}

      - name: Test image
        env:
            IMAGE_NAME: ${{ steps.prep.outputs.image_name }}
        run: |
            if [[ -f "docker-compose.test.yml" ]]; then
                docker-compose --file docker-compose.test.yml build
                docker-compose --file docker-compose.test.yml run sut
            fi

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1 
        with:
          username: nzeilemaker
          password: ${{ secrets.DOCKERHUB }}

      - name: Push image
        if: github.ref == 'refs/heads/master'
        run: |
            docker push $DOCKER_REPO

      - name: Update MicroBadger
        if: github.ref == 'refs/heads/master'
        env:
            MICROBADGER: ${{ secrets.MICROBADGER }}            
        run: |
            curl -X POST $MICROBADGER